#!/usr/bin/env bash
# ============================================================
# Flowstral/QAAI — On-Premises Interactive Installer
# ============================================================
# This script:
# 1. Validates prerequisites (Docker, Docker Compose)
# 2. Prompts for PostgreSQL connection, domain, TLS, admin email
# 3. Generates .env from .env.template
# 4. Tests database connectivity
# 5. Runs database migrations
# 6. Creates the initial admin account
# 7. Starts the application
#
# Usage:
#   chmod +x install.sh
#   ./install.sh

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo -e "${BLUE}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║      Flowstral/QAAI On-Premises Installer        ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════════╝${NC}"
echo ""

# ==================== Prerequisites ====================

echo -e "${YELLOW}[1/7] Checking prerequisites...${NC}"

if ! command -v docker &>/dev/null; then
    echo -e "${RED}✗ Docker is not installed. Please install Docker 24+ first.${NC}"
    echo "  → https://docs.docker.com/engine/install/"
    exit 1
fi
echo -e "${GREEN}✓ Docker found: $(docker --version)${NC}"

if ! docker compose version &>/dev/null; then
    echo -e "${RED}✗ Docker Compose v2 is not installed.${NC}"
    echo "  → Install via: docker compose plugin or standalone binary"
    exit 1
fi
echo -e "${GREEN}✓ Docker Compose found: $(docker compose version --short)${NC}"

# Check if .env already exists
if [ -f "${SCRIPT_DIR}/.env" ]; then
    echo -e "${YELLOW}⚠ .env file already exists. Overwrite? (y/N)${NC}"
    read -r overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "Keeping existing .env. Skipping configuration prompts."
        echo ""
        echo -e "${YELLOW}[5/7] Testing database connectivity...${NC}"
        # shellcheck source=/dev/null
        source "${SCRIPT_DIR}/.env"
        # Skip to step 5
        goto_step5=true
    fi
fi

if [ "${goto_step5:-false}" != "true" ]; then

# ==================== Database Configuration ====================

echo ""
echo -e "${YELLOW}[2/7] Database Configuration${NC}"
echo "  QAAI requires PostgreSQL 14+. You must provide an existing database."
echo ""

read -rp "  PostgreSQL host: " DB_HOST
read -rp "  PostgreSQL port [5432]: " DB_PORT
DB_PORT=${DB_PORT:-5432}
read -rp "  Database name [qaai]: " DB_NAME
DB_NAME=${DB_NAME:-qaai}
read -rp "  Database user: " DB_USER
read -rsp "  Database password: " DB_PASSWORD
echo ""
read -rp "  SSL mode [require]: " DB_SSL_MODE
DB_SSL_MODE=${DB_SSL_MODE:-require}

DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}"

# ==================== Domain & TLS ====================

echo ""
echo -e "${YELLOW}[3/7] Domain & TLS Configuration${NC}"
echo ""

read -rp "  Domain name (e.g., qaai.yourcompany.com): " DOMAIN

echo "  TLS certificate paths (PEM format):"
read -rp "    Certificate path [./certs/cert.pem]: " TLS_CERT_PATH
TLS_CERT_PATH=${TLS_CERT_PATH:-./certs/cert.pem}
read -rp "    Private key path [./certs/key.pem]: " TLS_KEY_PATH
TLS_KEY_PATH=${TLS_KEY_PATH:-./certs/key.pem}

# Create certs directory
mkdir -p "${SCRIPT_DIR}/certs"

# ==================== Admin Account ====================

echo ""
echo -e "${YELLOW}[4/7] Initial Admin Account${NC}"
echo ""

read -rp "  Admin email: " ADMIN_EMAIL
read -rp "  Admin name [Platform Admin]: " ADMIN_NAME
ADMIN_NAME=${ADMIN_NAME:-Platform Admin}
read -rsp "  Admin password (min 8 chars): " ADMIN_PASSWORD
echo ""
read -rp "  Organization name: " ORG_NAME

# ==================== Generate Secrets ====================

echo ""
echo -e "${YELLOW}Generating security keys...${NC}"

APP_SECRET_KEY=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)
# Generate Fernet key using Python if available, otherwise use openssl
if command -v python3 &>/dev/null; then
    FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null || openssl rand -base64 32)
else
    FERNET_KEY=$(openssl rand -base64 32)
fi

echo -e "${GREEN}✓ Security keys generated${NC}"

# ==================== Generate .env ====================

cat > "${SCRIPT_DIR}/.env" <<EOF
# Generated by install.sh on $(date -Iseconds)
# Flowstral/QAAI On-Premises Configuration

# Database
DATABASE_URL=${DATABASE_URL}
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_SSL_MODE=${DB_SSL_MODE}

# Security
APP_SECRET_KEY=${APP_SECRET_KEY}
JWT_SECRET=${JWT_SECRET}
FERNET_KEY=${FERNET_KEY}

# Application
APP_ENV=production
LOG_LEVEL=INFO
AUDIT_MODE=strict
AUTO_MIGRATE=true
SEED_DEMO_DATA=false

# Domain & TLS
DOMAIN=${DOMAIN}
VITE_API_URL=https://${DOMAIN}/api
TLS_CERT_PATH=${TLS_CERT_PATH}
TLS_KEY_PATH=${TLS_KEY_PATH}
HTTPS_PORT=443
HTTP_PORT=80
BACKEND_PORT=8000
CORS_ORIGINS=https://${DOMAIN}
ALLOWED_HOSTS=${DOMAIN}

# AI (Optional — leave blank to disable, users configure via Settings)
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
LLM_PROVIDER=openai

# SSO (Optional)
SAML_SP_ENTITY_ID=https://${DOMAIN}/api/auth/sso/saml
SAML_SP_ACS_URL=https://${DOMAIN}/api/auth/sso/saml/acs

# Image
IMAGE_TAG=latest

# Admin
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_NAME=${ADMIN_NAME}
ORG_NAME=${ORG_NAME}
EOF

chmod 600 "${SCRIPT_DIR}/.env"
echo -e "${GREEN}✓ .env file generated (permissions: 600)${NC}"

fi # end of goto_step5 skip

# ==================== Test Database ====================

echo ""
echo -e "${YELLOW}[5/7] Testing database connectivity...${NC}"

# shellcheck source=/dev/null
source "${SCRIPT_DIR}/.env"

# Quick connectivity test using docker
if docker run --rm --network host postgres:16-alpine \
    pg_isready -h "${DB_HOST}" -p "${DB_PORT}" -U "${DB_USER}" -d "${DB_NAME}" &>/dev/null; then
    echo -e "${GREEN}✓ Database connection successful${NC}"
else
    echo -e "${YELLOW}⚠ Could not verify database connectivity (may work when containers start).${NC}"
    echo "  Ensure PostgreSQL is running at ${DB_HOST}:${DB_PORT}"
fi

# ==================== Pull Images ====================

echo ""
echo -e "${YELLOW}[6/7] Building / pulling container images...${NC}"

cd "${SCRIPT_DIR}"
docker compose -f docker-compose.onprem.yml build --no-cache 2>&1 || {
    echo -e "${YELLOW}⚠ Build failed — attempting to pull pre-built images...${NC}"
    docker compose -f docker-compose.onprem.yml pull 2>&1 || true
}

# ==================== Start Application ====================

echo ""
echo -e "${YELLOW}[7/7] Starting Flowstral/QAAI...${NC}"

docker compose -f docker-compose.onprem.yml up -d

# Wait for backend to be healthy
echo "Waiting for backend to be ready..."
for i in {1..30}; do
    if curl -sf "http://localhost:${BACKEND_PORT:-8000}/health" &>/dev/null; then
        echo -e "${GREEN}✓ Backend is healthy${NC}"
        break
    fi
    sleep 2
    echo -n "."
done
echo ""

# ==================== Create Admin User ====================

echo -e "${YELLOW}Creating admin account...${NC}"

# Use the signup API to create the initial admin
SIGNUP_RESPONSE=$(curl -sf -X POST "http://localhost:${BACKEND_PORT:-8000}/api/auth/signup" \
    -H "Content-Type: application/json" \
    -d "{
        \"email\": \"${ADMIN_EMAIL}\",
        \"password\": \"${ADMIN_PASSWORD}\",
        \"name\": \"${ADMIN_NAME}\",
        \"org_name\": \"${ORG_NAME}\"
    }" 2>/dev/null) || true

if echo "${SIGNUP_RESPONSE}" | grep -q '"token"'; then
    echo -e "${GREEN}✓ Admin account created: ${ADMIN_EMAIL}${NC}"
else
    echo -e "${YELLOW}⚠ Admin account creation returned: ${SIGNUP_RESPONSE}${NC}"
    echo "  You may need to create the admin account manually."
fi

# ==================== Done ====================

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         Installation Complete!                    ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BLUE}Application URL:${NC}  https://${DOMAIN}"
echo -e "  ${BLUE}Admin Email:${NC}      ${ADMIN_EMAIL}"
echo -e "  ${BLUE}Backend Health:${NC}   http://localhost:${BACKEND_PORT:-8000}/health"
echo ""
echo -e "  ${YELLOW}Next Steps:${NC}"
echo "  1. Ensure TLS certificates are at: ${TLS_CERT_PATH} and ${TLS_KEY_PATH}"
echo "  2. Configure DNS: ${DOMAIN} → this server's IP"
echo "  3. (Optional) Configure SSO: Settings → Authentication → SSO"
echo "  4. (Optional) Add AI keys: Settings → AI Configuration"
echo ""
echo -e "  ${YELLOW}Commands:${NC}"
echo "  docker compose -f docker-compose.onprem.yml logs -f    # View logs"
echo "  docker compose -f docker-compose.onprem.yml restart     # Restart"
echo "  docker compose -f docker-compose.onprem.yml down        # Stop"
echo ""
