/**
 * Code Generator Functions
 *
 * Extracted from UnifiedWorkflowEditor.tsx.
 * Functions that generate code output (Python/Playwright, API, DB, Performance, Manual, ISTQB, Gherkin, Markdown).
 *
 * NOTE: generateAutomationCode is very large (~2000 lines) and remains in UnifiedWorkflowEditor.tsx
 * because it heavily references convertSelector and escapeForPython in complex template-literal code
 * generation that makes extraction fragile. The other generators are extracted here.
 */

import type { UnifiedTestCase, StepAssertion, TestStep } from '../types/workflow-editor.types';
import { convertSelector } from './selector-utils';
import { getStepDescription } from './step-helpers';
import { API_BASE_URL } from '@/lib/api-config';

// ============================================================================
// HELPER: Escape text for Python strings
// ============================================================================

/**
 * Helper function to escape text for Python strings (handles newlines, quotes, special chars, emojis)
 */
export function escapeForPython(text: string): string {
  if (!text) return '';
  return text
    .replace(/\\/g, '\\\\')     // Escape backslashes first
    .replace(/"/g, '\\"')       // Escape double quotes
    .replace(/\n/g, '\\n')      // Escape newlines
    .replace(/\r/g, '\\r')      // Escape carriage returns
    .replace(/\t/g, '\\t')      // Escape tabs
    .replace(/[^\x00-\x7F]/g, '') // Strip non-ASCII (emojis, unicode) for Windows compatibility
    .trim()                     // Remove leading/trailing whitespace after emoji removal
    .slice(0, 100);             // Limit length to avoid huge selectors
}

// ============================================================================
// ASSERTION CODE GENERATION
// ============================================================================

/**
 * Generate Playwright assertion code from structured assertion
 */
export function generateAssertionCode(assertion: StepAssertion, step: TestStep, stepIndex: number, indent: string): string {
  let code = '';
  const target = assertion.target || step.selector || '';
  const expected = assertion.expected || '';
  const selector = convertSelector(target);

  code += `${indent}# Verify: ${step.expectedResult || assertion.type}\n`;

  switch (assertion.type) {
    case 'element_visible':
      code += `${indent}expect(page.${selector}).to_be_visible()\n`;
      break;
    case 'element_hidden':
      code += `${indent}expect(page.${selector}).to_be_hidden()\n`;
      break;
    case 'text_contains':
      if (target) {
        code += `${indent}expect(page.${selector}).to_contain_text("${expected}")\n`;
      } else {
        code += `${indent}expect(page.locator("body")).to_contain_text("${expected}")\n`;
      }
      break;
    case 'text_equals':
      code += `${indent}expect(page.${selector}).to_have_text("${expected}")\n`;
      break;
    case 'url_contains':
      code += `${indent}expect(page).to_have_url(re.compile(r".*${expected}.*"))\n`;
      break;
    case 'url_equals':
      code += `${indent}expect(page).to_have_url("${expected}")\n`;
      break;
    case 'value_equals':
      code += `${indent}expect(page.${selector}).to_have_value("${expected}")\n`;
      break;
    case 'element_enabled':
      code += `${indent}expect(page.${selector}).to_be_enabled()\n`;
      break;
    case 'element_disabled':
      code += `${indent}expect(page.${selector}).to_be_disabled()\n`;
      break;
    case 'count_equals':
      code += `${indent}expect(page.${selector}).to_have_count(${expected || 1})\n`;
      break;
    case 'page_title':
      code += `${indent}expect(page).to_have_title("${expected}")\n`;
      break;
    case 'toast_message':
      // Common toast selectors
      code += `${indent}expect(page.locator('[role="alert"], .toast, .notification, [class*="toast"], [class*="snackbar"]').filter(has_text="${expected}")).to_be_visible(timeout=5000)\n`;
      break;
    case 'attribute_equals': {
      const [attr, val] = expected.split('=');
      code += `${indent}expect(page.${selector}).to_have_attribute("${attr || 'class'}", "${val || ''}")\n`;
      break;
    }
    case 'custom':
      code += `${indent}# Custom assertion: ${expected || 'verify expected result'}\n`;
      code += `${indent}pass  # Implement custom verification\n`;
      break;
    default:
      code += `${indent}# TODO: Verify ${assertion.type}\n`;
  }

  return code;
}

// ============================================================================
// API CODE GENERATION
// ============================================================================

export function generateAPICode(tc: UnifiedTestCase, safeName: string): string {
  let code = `"""
${tc.name} - API Test
${tc.description || 'Generated by QAAI'}
"""

import pytest
import requests

BASE_URL = "${tc.settings.baseUrl || API_BASE_URL}"

class Test${safeName.replace(/_/g, '')}:
`;

  const apiSteps = tc.steps.filter(s => s.type === 'api' && s.enabled);

  if (apiSteps.length === 0) {
    code += `    def test_placeholder(self):
        """No API steps defined"""
        pass
`;
  } else {
    apiSteps.forEach((step, index) => {
      const stepName = step.name.replace(/[^a-z0-9]+/gi, '_').toLowerCase();
      code += `
    def test_${index + 1}_${stepName}(self):
        """${step.name}"""
        response = requests.${(step.method || 'GET').toLowerCase()}(
            f"{BASE_URL}${step.endpoint || '/'}",
            ${step.body ? `json=${step.body},` : ''}
            headers=${JSON.stringify(step.headers || {})}
        )
        assert response.status_code in [200, 201, 204], f"Expected 2xx, got {response.status_code}"
`;
      if (step.storeAs) {
        code += `        ${step.storeAs} = response.json()\n`;
      }
    });
  }

  return code;
}

// ============================================================================
// DATABASE CODE GENERATION
// ============================================================================

export function generateDBCode(tc: UnifiedTestCase, safeName: string): string {
  let code = `"""
${tc.name} - Database Test
${tc.description || 'Generated by QAAI'}
"""

import pytest
import psycopg2
# from pymongo import MongoClient  # For MongoDB
# from simple_salesforce import Salesforce  # For SOQL

class Test${safeName.replace(/_/g, '')}:
`;

  const dbSteps = tc.steps.filter(s => (s.type === 'db_query' || s.type === 'db_assert') && s.enabled);

  if (dbSteps.length === 0) {
    code += `    def test_placeholder(self):
        """No database steps defined"""
        pass
`;
  } else {
    dbSteps.forEach((step, index) => {
      const stepName = step.name.replace(/[^a-z0-9]+/gi, '_').toLowerCase();
      code += `
    def test_${index + 1}_${stepName}(self):
        """${step.name}"""
        # Connection would be configured via environment variables
        query = """${step.query || 'SELECT 1'}"""
        # Execute query and verify results
        # result = cursor.execute(query)
        # assert result is not None
        pass
`;
    });
  }

  return code;
}

// ============================================================================
// PERFORMANCE CODE GENERATION
// ============================================================================

export function generatePerformanceCode(tc: UnifiedTestCase, safeName: string): string {
  return `// K6 Performance Test Script
// ${tc.name}
// ${tc.description || 'Generated by QAAI'}

import http from 'k6/http';
import { check, sleep } from 'k6';
import { browser } from 'k6/experimental/browser';

export const options = {
  scenarios: {
    ui_test: {
      executor: 'shared-iterations',
      vus: 10,
      iterations: 50,
      options: { browser: { type: 'chromium' } },
    },
  },
  thresholds: {
    checks: ['rate>0.95'],
    browser_web_vital_lcp: ['p(95)<2500'],
  },
};

export default async function () {
  const page = browser.newPage();

  try {
${tc.steps.filter(s => s.enabled).map((step) => {
  if (step.type === 'navigate') return `    await page.goto('${step.url || tc.settings.baseUrl || ''}');`;
  if (step.type === 'click' && step.selector) return `    await page.locator('${step.selector}').click();`;
  if ((step.type === 'input' || step.type === 'fill' as any) && step.selector) return `    await page.locator('${step.selector}').fill('${step.value || ''}');`;
  return '';
}).filter(Boolean).join('\n')}
  } finally {
    page.close();
  }

  sleep(1);
}
`;
}

// ============================================================================
// MANUAL DOCUMENTATION GENERATION
// ============================================================================

export function generateManualDoc(tc: UnifiedTestCase): string {
  let doc = `# ${tc.name}\n\n`;
  doc += `**Description:** ${tc.description || 'N/A'}\n\n`;
  doc += `**Tags:** ${tc.tags.join(', ') || 'None'}\n\n`;
  doc += `**Timeout:** ${tc.settings.timeout}ms\n\n`;
  doc += `---\n\n`;
  doc += `## Test Steps\n\n`;

  tc.steps.forEach((step, index) => {
    if (!step.enabled) {
      doc += `### ~~Step ${index + 1}: ${step.name}~~ (Disabled)\n\n`;
      return;
    }

    doc += `### Step ${index + 1}: ${step.name}\n\n`;
    doc += `**Action:** ${step.manualAction || getStepDescription(step)}\n\n`;
    doc += `**Expected Result:** ${step.expectedResult || 'TBD'}\n\n`;
    doc += `**Status:** [ ] Pass  [ ] Fail  [ ] Blocked\n\n`;
    doc += `---\n\n`;
  });

  return doc;
}

// ============================================================================
// ISTQB FORMAT GENERATION
// ============================================================================

export function generateISTQBFormat(tc: UnifiedTestCase): string {
  let doc = `\u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510
\u2502                    TEST CASE SPECIFICATION                       \u2502
\u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518

TEST CASE ID: ${tc.id}
TEST CASE NAME: ${tc.name}
VERSION: ${tc.metadata.version}
CREATED: ${new Date(tc.metadata.createdAt).toLocaleDateString()}
AUTHOR: ${tc.metadata.author || 'N/A'}

\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501

DESCRIPTION:
${tc.description || 'No description provided'}

TAGS: ${tc.tags.join(', ') || 'None'}

\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501

PRECONDITIONS:
`;

  if (tc.preconditions?.length > 0) {
    tc.preconditions.forEach((pre, idx) => {
      doc += `${idx + 1}. Execute test case: ${pre.testCaseName} (${pre.enabled ? 'Enabled' : 'Disabled'})\n`;
    });
  } else {
    doc += `\u2022 None specified\n`;
  }

  doc += `
\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501

TEST STEPS:
\u250c\u2500\u2500\u2500\u2500\u252c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u252c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u252c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510
\u2502 #  \u2502 ACTION                 \u2502 EXPECTED RESULT        \u2502 STATUS   \u2502
\u251c\u2500\u2500\u2500\u2500\u253c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u253c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u253c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2524
`;

  tc.steps.forEach((step, index) => {
    const action = (step.manualAction || getStepDescription(step)).slice(0, 22).padEnd(22);
    const expected = (step.expectedResult || 'Verify success').slice(0, 22).padEnd(22);
    const status = step.enabled ? '[ ]      ' : 'SKIP     ';
    doc += `\u2502 ${String(index + 1).padStart(2)} \u2502 ${action} \u2502 ${expected} \u2502 ${status}\u2502\n`;
  });

  doc += `\u2514\u2500\u2500\u2500\u2500\u2534\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2534\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2534\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518

\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501

TEST DATA:
${tc.variables.length > 0
  ? tc.variables.map(v => `\u2022 ${v.name}: ${v.value}`).join('\n')
  : '\u2022 No test data specified'}

ENVIRONMENT:
\u2022 Base URL: ${tc.settings.baseUrl || 'Not specified'}
\u2022 Timeout: ${tc.settings.timeout}ms
\u2022 Retries: ${tc.settings.retries}

\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501\u2501

EXECUTION SUMMARY:
\u2022 Total Steps: ${tc.steps.length}
\u2022 Enabled Steps: ${tc.steps.filter(s => s.enabled).length}
\u2022 Disabled Steps: ${tc.steps.filter(s => !s.enabled).length}

RESULT: [ ] PASS  [ ] FAIL  [ ] BLOCKED

NOTES:
_________________________________________________________________
`;

  return doc;
}

// ============================================================================
// GHERKIN FORMAT GENERATION
// ============================================================================

export function generateGherkinFormat(tc: UnifiedTestCase): string {
  const tagLine = tc.tags.length > 0 ? tc.tags.map(t => `@${t.replace(/\s+/g, '_')}`).join(' ') : '@automated';

  let doc = `${tagLine}
Feature: ${tc.name}
  ${tc.description || 'Automated test case'}

`;

  // Add background for preconditions if any
  if (tc.preconditions?.length > 0) {
    doc += `  Background:
    Given the following test cases have been executed:
`;
    tc.preconditions.forEach(pre => {
      if (pre.enabled) {
        doc += `      | ${pre.testCaseName} |
`;
      }
    });
    doc += `
`;
  }

  doc += `  Scenario: ${tc.name}
`;

  // Group steps by type for better Gherkin flow
  let hasGiven = false;
  let hasWhen = false;

  tc.steps.forEach((step, index) => {
    if (!step.enabled) {
      doc += `    # DISABLED: ${step.name}\n`;
      return;
    }

    let keyword = 'And';

    // First navigate is Given
    if (step.type === 'navigate' && !hasGiven) {
      keyword = 'Given';
      hasGiven = true;
    }
    // Actions (click, input, fill, select) are When
    else if (['click', 'input', 'fill', 'select', 'hover'].includes(step.type) && !hasWhen) {
      keyword = 'When';
      hasWhen = true;
    }
    // Assertions are Then
    else if (['assert', 'verify'].includes(step.type)) {
      keyword = 'Then';
    }
    // Continue with And for same type
    else if (hasGiven && step.type === 'navigate') {
      keyword = 'And';
    }
    else if (hasWhen && ['click', 'input', 'fill', 'select', 'hover'].includes(step.type)) {
      keyword = 'And';
    }

    const description = getStepDescription(step);
    doc += `    ${keyword} ${description}\n`;

    if (step.expectedResult) {
      doc += `    Then ${step.expectedResult}\n`;
    }
  });

  doc += `


  # Test Data
`;

  if (tc.variables.length > 0) {
    doc += `  Examples:
    | variable | value |
`;
    tc.variables.forEach(v => {
      doc += `    | ${v.name} | ${v.value} |
`;
    });
  }

  return doc;
}

// ============================================================================
// MARKDOWN FORMAT GENERATION
// ============================================================================

export function generateMarkdownFormat(tc: UnifiedTestCase): string {
  let doc = `# ${tc.name}

> ${tc.description || 'No description provided'}

**Test ID:** \`${tc.id}\`
**Tags:** ${tc.tags.map(t => `\`${t}\``).join(', ') || 'None'}
**Created:** ${new Date(tc.metadata.createdAt).toLocaleDateString()}

---

## Preconditions

`;

  if (tc.preconditions?.length > 0) {
    tc.preconditions.forEach((pre, idx) => {
      const icon = pre.enabled ? 'YES' : 'SKIP';
      doc += `${idx + 1}. [${icon}] **${pre.testCaseName}**\n`;
    });
  } else {
    doc += `_No preconditions defined_\n`;
  }

  doc += `
---

## Test Steps

| # | Step | Action | Expected Result | Status |
|---|------|--------|-----------------|--------|
`;

  tc.steps.forEach((step, index) => {
    const status = step.enabled ? 'TODO' : 'Skip';
    const action = step.manualAction || getStepDescription(step);
    const expected = step.expectedResult || 'Verify success';
    doc += `| ${index + 1} | ${step.name} | ${action} | ${expected} | ${status} |\n`;
  });

  doc += `
---

## Test Configuration

- **Base URL:** ${tc.settings.baseUrl || 'Not specified'}
- **Timeout:** ${tc.settings.timeout}ms
- **Retries:** ${tc.settings.retries}
- **Parallelizable:** ${tc.settings.parallelizable ? 'Yes' : 'No'}

`;

  if (tc.variables.length > 0) {
    doc += `## Test Data

| Variable | Value | Type |
|----------|-------|------|
`;
    tc.variables.forEach(v => {
      doc += `| ${v.name} | ${v.value} | ${v.type} |\n`;
    });
  }

  doc += `
---

## Execution Result

- [ ] **PASS** - All steps completed successfully
- [ ] **FAIL** - One or more steps failed
- [ ] **BLOCKED** - Unable to execute

**Notes:**
_Add execution notes here..._
`;

  return doc;
}
