"""
FLOWSTRAL CODE GENERATOR
========================
Generates robust Playwright test code using the Flowstral Engine.

Instead of generating raw Playwright selectors:
    page.locator('[data-aura-rendered-by="123:0"]').click()

We generate intent-based engine calls:
    engine.click(text="Save", role="button")
"""

import re
import json
from typing import List, Dict, Any, Optional
from dataclasses import dataclass


@dataclass
class TestStep:
    """Represents a single test step."""
    action: str  # click, fill, navigate, hover, etc.
    description: str  # Human-readable description
    target: Optional[str] = None  # Target element description
    value: Optional[str] = None  # Value for inputs
    selector: Optional[str] = None  # Original recorded selector (as hint)
    url: Optional[str] = None  # For navigate actions
    metadata: Dict = None  # Additional data


class FlowstralCodeGenerator:
    """
    Generates robust Python test code using the Flowstral Engine.
    
    The generated code uses semantic element finding instead of
    brittle CSS selectors, making tests more maintainable and
    self-healing.
    """
    
    def __init__(self, test_name: str, app_type: str = "auto"):
        self.test_name = self._sanitize_name(test_name)
        self.app_type = app_type
        self.steps: List[TestStep] = []
        self.imports = set()
        self.setup_code = []
    
    def _sanitize_name(self, name: str) -> str:
        """Sanitize test name for Python."""
        name = re.sub(r'[^a-zA-Z0-9_]', '_', name.lower())
        if name[0].isdigit():
            name = 'test_' + name
        return name
    
    def add_step(
        self,
        action: str,
        description: str,
        target: str = None,
        value: str = None,
        selector: str = None,
        url: str = None,
        **metadata
    ):
        """Add a test step."""
        self.steps.append(TestStep(
            action=action,
            description=description,
            target=target,
            value=value,
            selector=selector,
            url=url,
            metadata=metadata or {}
        ))
    
    def generate(self) -> str:
        """Generate the complete test file."""
        code_lines = []
        
        # === IMPORTS ===
        code_lines.extend(self._generate_imports())
        code_lines.append("")
        
        # === FLOWSTRAL ENGINE CLASS (embedded for portability) ===
        code_lines.extend(self._generate_embedded_engine())
        code_lines.append("")
        
        # === TEST FUNCTION ===
        code_lines.extend(self._generate_test_function())
        
        # === MAIN BLOCK ===
        code_lines.extend(self._generate_main_block())
        
        return "\n".join(code_lines)
    
    def _generate_imports(self) -> List[str]:
        """Generate import statements."""
        return [
            '"""',
            f'Test: {self.test_name}',
            f'Generated by Flowstral Engine',
            f'App Type: {self.app_type}',
            '"""',
            '',
            'import sys',
            'import time',
            'import re',
            'from typing import Optional, List, Dict, Any',
            'from playwright.sync_api import sync_playwright, Page, Locator',
            'import pytest',
            '',
        ]
    
    def _generate_embedded_engine(self) -> List[str]:
        """Generate a minimal embedded version of the engine for portability."""
        return [
            '# ============================================================',
            '# FLOWSTRAL ENGINE (embedded for portability)',
            '# ============================================================',
            '',
            'class FlowstralEngine:',
            '    """Robust automation engine for Salesforce and enterprise apps."""',
            '    ',
            '    def __init__(self, page: Page, app_type: str = "salesforce", verbose: bool = True):',
            '        self.page = page',
            '        self.app_type = app_type',
            '        self.verbose = verbose',
            '        self._configure_app()',
            '    ',
            '    def _log(self, msg: str):',
            '        if self.verbose:',
            '            print(f"[FLOWSTRAL] {msg}")',
            '    ',
            '    def _configure_app(self):',
            '        """Configure for specific app type."""',
            '        if self.app_type == "salesforce":',
            '            self.loading_selectors = [',
            '                "lightning-spinner", ".slds-spinner",',
            '                ".slds-spinner_container:not(.slds-hide)", "[aria-busy=\'true\']"',
            '            ]',
            '            self.component_selectors = {',
            '                "app_launcher": ["div.slds-icon-waffle", "button.slds-icon-waffle", ".appLauncher button"],',
            '                "app_launcher_search": ["one-app-launcher-menu input[type=\'search\']", "input[placeholder*=\'Search apps\']"],',
            '                "save_button": ["button[name=\'SaveEdit\']", "button:has-text(\'Save\')", ".slds-modal__footer button:has-text(\'Save\')"],',
            '            }',
            '        else:',
            '            self.loading_selectors = [".loading", ".spinner", "[aria-busy=\'true\']"]',
            '            self.component_selectors = {}',
            '    ',
            '    # === WAITING ===',
            '    ',
            '    def wait_for_ready(self, timeout: int = 15000):',
            '        """Wait for page to be ready."""',
            '        try:',
            '            self.page.wait_for_load_state("domcontentloaded", timeout=timeout)',
            '        except:',
            '            pass',
            '        ',
            '        # Wait for spinners to disappear',
            '        start = time.time()',
            '        while (time.time() - start) < (timeout / 1000):',
            '            has_spinner = False',
            '            for sel in self.loading_selectors:',
            '                try:',
            '                    if self.page.locator(sel).is_visible(timeout=500):',
            '                        has_spinner = True',
            '                        break',
            '                except:',
            '                    pass',
            '            if not has_spinner:',
            '                break',
            '            time.sleep(0.3)',
            '        ',
            '        time.sleep(0.2)',
            '    ',
            '    # === ELEMENT FINDING ===',
            '    ',
            '    def _find_element(self, ',
            '                      text: str = None, ',
            '                      role: str = None, ',
            '                      label: str = None,',
            '                      placeholder: str = None,',
            '                      title: str = None,',
            '                      selector_hint: str = None,',
            '                      component: str = None,',
            '                      timeout: int = 10000) -> Optional[Locator]:',
            '        """Find element using smart strategies."""',
            '        strategies = []',
            '        ',
            '        # Strategy 1: App-specific component',
            '        if component and component in self.component_selectors:',
            '            for sel in self.component_selectors[component]:',
            '                strategies.append(("component", self.page.locator(sel)))',
            '        ',
            '        # Strategy 2: Role + name (most reliable)',
            '        if role and text:',
            '            strategies.append(("role+text", self.page.get_by_role(role, name=text)))',
            '            strategies.append(("role+text_contains", self.page.get_by_role(role, name=re.compile(text, re.IGNORECASE))))',
            '        ',
            '        # Strategy 3: Label-based (for inputs)',
            '        if label:',
            '            strategies.append(("label", self.page.get_by_label(label)))',
            '            strategies.append(("label_contains", self.page.get_by_label(re.compile(label, re.IGNORECASE))))',
            '        ',
            '        # Strategy 4: Placeholder',
            '        if placeholder:',
            '            strategies.append(("placeholder", self.page.get_by_placeholder(placeholder)))',
            '            strategies.append(("placeholder_contains", self.page.get_by_placeholder(re.compile(placeholder, re.IGNORECASE))))',
            '        ',
            '        # Strategy 5: Text content',
            '        if text:',
            '            strategies.append(("text_exact", self.page.get_by_text(text, exact=True)))',
            '            strategies.append(("text_contains", self.page.get_by_text(text)))',
            '        ',
            '        # Strategy 6: Title attribute',
            '        if title:',
            '            strategies.append(("title", self.page.get_by_title(title)))',
            '        ',
            '        # Strategy 7: Selector hint (fallback)',
            '        if selector_hint:',
            '            try:',
            '                if selector_hint.startswith("page.get_by_"):',
            '                    method_name = selector_hint.split("(")[0].replace("page.", "")',
            '                    method_arg = selector_hint.split("(", 1)[1].rstrip(")")',
            '                    method_arg = method_arg.strip(\'"\').strip("\'")',
            '                    strategies.append(("hint", getattr(self.page, method_name)(method_arg)))',
            '                elif selector_hint.startswith("page.locator("):',
            '                    loc_arg = selector_hint.split("(", 1)[1].rstrip(")")',
            '                    loc_arg = loc_arg.strip(\'"\').strip("\'")',
            '                    strategies.append(("hint", self.page.locator(loc_arg)))',
            '                elif not selector_hint.startswith("page."):',
            '                    strategies.append(("hint", self.page.locator(selector_hint)))',
            '            except:',
            '                pass',
            '        ',
            '        # Try each strategy',
            '        for name, locator in strategies:',
            '            try:',
            '                if locator.count() > 0:',
            '                    if locator.first.is_visible(timeout=2000):',
            '                        self._log(f"   Found via: {name}")',
            '                        return locator.first',
            '                    elif locator.count() > 1:',
            '                        # Try visible filter',
            '                        visible = locator.locator("visible=true")',
            '                        if visible.count() > 0:',
            '                            self._log(f"   Found via: {name} (visible)")',
            '                            return visible.first',
            '            except:',
            '                continue',
            '        ',
            '        return None',
            '    ',
            '    # === ACTIONS ===',
            '    ',
            '    def click(self, ',
            '              text: str = None,',
            '              role: str = None,',
            '              label: str = None,',
            '              title: str = None,',
            '              component: str = None,',
            '              selector_hint: str = None,',
            '              timeout: int = 10000,',
            '              description: str = None) -> bool:',
            '        """Click an element by intent."""',
            '        desc = description or text or label or "element"',
            '        self._log(f"Click: {desc}")',
            '        ',
            '        self.wait_for_ready(timeout=5000)',
            '        ',
            '        # Retry loop',
            '        for attempt in range(3):',
            '            element = self._find_element(',
            '                text=text, role=role, label=label, title=title,',
            '                component=component, selector_hint=selector_hint, timeout=timeout',
            '            )',
            '            ',
            '            if not element:',
            '                if attempt < 2:',
            '                    self._log(f"   [RETRY {attempt+1}] Waiting 2s...")',
            '                    time.sleep(2)',
            '                    continue',
            '                raise Exception(f"Element not found: {desc}")',
            '            ',
            '            try:',
            '                element.scroll_into_view_if_needed()',
            '            except:',
            '                pass',
            '            ',
            '            try:',
            '                element.click(force=True, timeout=5000)',
            '                self._log(f"   [+] Clicked")',
            '                self.wait_for_ready(timeout=5000)',
            '                return True',
            '            except Exception as e:',
            '                if attempt < 2:',
            '                    self._log(f"   [RETRY {attempt+1}] Click failed, retrying...")',
            '                    time.sleep(1)',
            '                    continue',
            '                raise',
            '        ',
            '        return False',
            '    ',
            '    def fill(self,',
            '             value: str,',
            '             label: str = None,',
            '             placeholder: str = None,',
            '             role: str = "textbox",',
            '             selector_hint: str = None,',
            '             timeout: int = 10000,',
            '             description: str = None) -> bool:',
            '        """Fill an input field."""',
            '        desc = description or label or placeholder or "input"',
            '        self._log(f"Fill: {desc} = \'{value[:30]}...\'" if len(value) > 30 else f"Fill: {desc} = \'{value}\'")',
            '        ',
            '        self.wait_for_ready(timeout=5000)',
            '        ',
            '        for attempt in range(3):',
            '            element = self._find_element(',
            '                label=label, placeholder=placeholder, role=role,',
            '                selector_hint=selector_hint, timeout=timeout',
            '            )',
            '            ',
            '            if not element:',
            '                if attempt < 2:',
            '                    self._log(f"   [RETRY {attempt+1}] Waiting 1.5s...")',
            '                    time.sleep(1.5)',
            '                    continue',
            '                raise Exception(f"Input not found: {desc}")',
            '            ',
            '            try:',
            '                element.scroll_into_view_if_needed()',
            '            except:',
            '                pass',
            '            ',
            '            # Try multiple fill strategies',
            '            strategies = [',
            '                lambda: self._fill_click_fill(element, value),',
            '                lambda: self._fill_click_type(element, value),',
            '                lambda: self._fill_focus_type(element, value),',
            '            ]',
            '            ',
            '            for strategy in strategies:',
            '                try:',
            '                    strategy()',
            '                    self._log(f"   [+] Filled")',
            '                    return True',
            '                except:',
            '                    continue',
            '            ',
            '            if attempt < 2:',
            '                time.sleep(1)',
            '        ',
            '        raise Exception(f"Could not fill: {desc}")',
            '    ',
            '    def _fill_click_fill(self, element: Locator, value: str):',
            '        element.click(timeout=2000)',
            '        time.sleep(0.1)',
            '        element.fill("", timeout=1000)',
            '        element.fill(value, timeout=3000)',
            '    ',
            '    def _fill_click_type(self, element: Locator, value: str):',
            '        element.click(timeout=2000)',
            '        self.page.keyboard.press("Control+a")',
            '        element.type(value, delay=30)',
            '    ',
            '    def _fill_focus_type(self, element: Locator, value: str):',
            '        element.focus()',
            '        self.page.keyboard.press("Control+a")',
            '        self.page.keyboard.type(value)',
            '    ',
            '    def navigate(self, url: str):',
            '        """Navigate to URL."""',
            '        self._log(f"Navigate: {url}")',
            '        self.page.goto(url)',
            '        self.wait_for_ready()',
            '    ',
            '    def hover(self, text: str = None, selector_hint: str = None, skip_on_fail: bool = True):',
            '        """Hover over element (non-critical, skips on failure)."""',
            '        try:',
            '            element = self._find_element(text=text, selector_hint=selector_hint, timeout=3000)',
            '            if element:',
            '                element.hover(timeout=2000)',
            '                self._log(f"   Hovered: {text or \'element\'}")',
            '        except:',
            '            if skip_on_fail:',
            '                self._log(f"   [SKIP] Hover - non-critical")',
            '            else:',
            '                raise',
            '    ',
            '    # === SALESFORCE-SPECIFIC ===',
            '    ',
            '    def sf_open_app(self, app_name: str):',
            '        """Open Salesforce app from App Launcher."""',
            '        self._log(f"[SF] Opening app: {app_name}")',
            '        app_name = app_name.replace(\'"\', \'\\\\"\')',
            '        ',
            '        # Click waffle',
            '        self.click(component="app_launcher", description="App Launcher")',
            '        time.sleep(0.5)',
            '        ',
            '        # Wait for modal and search',
            '        for _ in range(10):',
            '            modal = self.page.locator("one-app-launcher-menu")',
            '            if modal.count() > 0 and modal.is_visible(timeout=1000):',
            '                break',
            '            time.sleep(0.5)',
            '        ',
            '        # Fill search',
            '        search = self._find_element(component="app_launcher_search", timeout=5000)',
            '        if search:',
            '            self._fill_click_fill(search, app_name)',
            '            time.sleep(0.5)',
            '        ',
            '        # Click result',
            '        result_selectors = [',
            '            f\'one-app-launcher-menu-item a:has-text("{app_name}")\',',
            '            f\'p.slds-truncate:has-text("{app_name}")\',',
            '            f\'mark:has-text("{app_name}")\',',
            '        ]',
            '        for sel in result_selectors:',
            '            try:',
            '                result = self.page.locator(sel).first',
            '                if result.is_visible(timeout=2000):',
            '                    result.click()',
            '                    self._log(f"   [+] Selected: {app_name}")',
            '                    self.wait_for_ready()',
            '                    return True',
            '            except:',
            '                continue',
            '        ',
            '        raise Exception(f"App not found: {app_name}")',
            '    ',
            '    def sf_global_search(self, text: str):',
            '        """Use Salesforce global search."""',
            '        self._log(f"[SF] Global search: {text}")',
            '        ',
            '        # Click search button',
            '        self.click(title="Search", description="Global Search")',
            '        time.sleep(0.5)',
            '        ',
            '        # Fill search',
            '        search = self._find_element(placeholder="Search...", timeout=5000)',
            '        if search:',
            '            self._fill_click_fill(search, text)',
            '            self.page.keyboard.press("Enter")',
            '            self.wait_for_ready()',
            '            return True',
            '        ',
            '        raise Exception("Search input not found")',
            '    ',
            '    def sf_click_tab(self, tab_name: str):',
            '        """Click a Salesforce record tab."""',
            '        self._log(f"[SF] Click tab: {tab_name}")',
            '        tab_name = tab_name.replace(\'"\', \'\\\\"\')',
            '        tab_selectors = [',
            '            f\'a[data-label="{tab_name}"]\',',
            '            f\'[role="tab"]:has-text("{tab_name}")\',',
            '            f\'lightning-tab-bar a:has-text("{tab_name}")\',',
            '        ]',
            '        for sel in tab_selectors:',
            '            try:',
            '                tab = self.page.locator(sel).first',
            '                if tab.is_visible(timeout=2000):',
            '                    tab.click()',
            '                    self._log(f"   [+] Clicked tab: {tab_name}")',
            '                    return True',
            '            except:',
            '                continue',
            '        raise Exception(f"Tab not found: {tab_name}")',
            '    ',
            '    def sf_save(self):',
            '        """Click Salesforce Save button."""',
            '        self.click(component="save_button", text="Save", role="button", description="Save")',
            '',
            '',
        ]
    
    def _generate_test_function(self) -> List[str]:
        """Generate the test function."""
        lines = [
            '# ============================================================',
            '# TEST FUNCTION',
            '# ============================================================',
            '',
            '@pytest.fixture(scope="function")',
            'def browser_context():',
            '    """Create browser context for test."""',
            '    with sync_playwright() as p:',
            '        browser = p.chromium.launch(headless=False, slow_mo=100)',
            '        context = browser.new_context(viewport={"width": 1920, "height": 1080})',
            '        yield context',
            '        context.close()',
            '        browser.close()',
            '',
            '',
            f'def test_{self.test_name}(browser_context):',
            f'    """Auto-generated test: {self.test_name}"""',
            '    page = browser_context.new_page()',
            f'    engine = FlowstralEngine(page, app_type="{self.app_type}")',
            '    ',
            '    step_num = 0',
            '    step_error = None',
            '    ',
            '    try:',
        ]
        
        # Generate steps
        for i, step in enumerate(self.steps, 1):
            lines.append(f'        # Step {i}: {step.description}')
            lines.append(f'        step_num = {i}')
            lines.append(f'        print(f"[+] Step {i}: {step.description}")')
            lines.extend(self._generate_step_code(step))
            lines.append('')
        
        # Exception handling
        lines.extend([
            '        print("\\n" + "="*50)',
            '        print("[SUCCESS] All steps completed!")',
            '        print("="*50)',
            '        ',
            '    except Exception as e:',
            '        step_error = e',
            '        print(f"\\n[FAIL] Step {step_num} failed: {e}")',
            '        ',
            '        # Take screenshot',
            '        try:',
            f'            screenshot_path = f"failure_step_{{step_num}}_{self.test_name}.png"',
            '            page.screenshot(path=screenshot_path)',
            '            print(f"Screenshot saved: {screenshot_path}")',
            '        except:',
            '            pass',
            '        ',
            '        raise step_error',
            '    ',
            '    finally:',
            '        # Keep browser open briefly for debugging',
            '        time.sleep(3)',
            '',
        ])
        
        return lines
    
    def _generate_step_code(self, step: TestStep) -> List[str]:
        """Generate code for a single step."""
        lines = []
        indent = '        '
        
        action = step.action.lower()
        
        if action == 'navigate':
            url = (step.url or step.value or '').replace('"', '\\"').replace("'", "\\'")
            lines.append(f'{indent}engine.navigate("{url}")')
            
        elif action == 'click':
            args = self._build_element_args(step)
            lines.append(f'{indent}engine.click({args})')
            
        elif action in ['fill', 'input', 'type']:
            value = (step.value or '').replace('\\', '\\\\').replace('"', '\\"').replace("'", "\\'")
            args = self._build_element_args(step, include_value=False)
            lines.append(f'{indent}engine.fill("{value}", {args})')
            
        elif action == 'hover':
            args = self._build_element_args(step)
            lines.append(f'{indent}engine.hover({args})')
            
        elif action == 'sf_open_app':
            app_name = (step.value or step.target or '').replace('"', '\\"')
            lines.append(f'{indent}engine.sf_open_app("{app_name}")')
            
        elif action == 'sf_global_search':
            search_text = (step.value or '').replace('"', '\\"')
            lines.append(f'{indent}engine.sf_global_search("{search_text}")')
            
        elif action == 'sf_click_tab':
            tab_name = (step.target or step.value or '').replace('"', '\\"')
            lines.append(f'{indent}engine.sf_click_tab("{tab_name}")')
            
        elif action == 'sf_save':
            lines.append(f'{indent}engine.sf_save()')
            
        elif action == 'wait':
            ms = step.value or '1000'
            lines.append(f'{indent}engine.page.wait_for_timeout({ms})')
            
        elif action == 'press_key':
            key = (step.value or 'Enter').replace('"', '\\"')
            lines.append(f'{indent}engine.page.keyboard.press("{key}")')
            
        else:
            # Generic action - try to map to click/fill
            if step.value:
                args = self._build_element_args(step, include_value=False)
                value = step.value.replace('\\', '\\\\').replace('"', '\\"').replace("'", "\\'")
                lines.append(f'{indent}engine.fill("{value}", {args})')
            else:
                args = self._build_element_args(step)
                lines.append(f'{indent}engine.click({args})')
        
        return lines
    
    def _build_element_args(self, step: TestStep, include_value: bool = True) -> str:
        """Build argument string for element finding."""
        args = []
        
        # Extract text from description
        desc = step.description or ''
        target = step.target or ''
        
        # Try to detect meaningful text
        text = None
        
        # Check for quoted text in description
        quotes_match = re.search(r'"([^"]+)"', desc)
        if quotes_match:
            text = quotes_match.group(1)
        elif target:
            text = target
        
        # Detect role from description
        role = None
        desc_lower = desc.lower()
        
        if 'button' in desc_lower or 'click' in desc_lower:
            role = 'button'
        elif 'input' in desc_lower or 'fill' in desc_lower:
            role = 'textbox'
        elif 'link' in desc_lower:
            role = 'link'
        elif 'tab' in desc_lower:
            role = 'tab'
        elif 'checkbox' in desc_lower:
            role = 'checkbox'
        
        # Build args
        if text:
            args.append(f'text="{text}"')
        
        if role:
            args.append(f'role="{role}"')
        
        # Add selector hint if available
        if step.selector:
            selector = step.selector.replace('"', '\\"')
            args.append(f'selector_hint="{selector}"')
        
        # Add description
        clean_desc = desc.replace('"', '\\"')[:50]
        args.append(f'description="{clean_desc}"')
        
        return ', '.join(args)
    
    def _generate_main_block(self) -> List[str]:
        """Generate if __name__ == '__main__' block."""
        return [
            '',
            '# ============================================================',
            '# MAIN EXECUTION',
            '# ============================================================',
            '',
            'if __name__ == "__main__":',
            '    # Run with pytest for better output',
            '    import subprocess',
            '    exit_code = subprocess.call(["python", "-m", "pytest", __file__, "-v", "-s", "--tb=short"])',
            '    sys.exit(exit_code)',
        ]


# ============================================================
# CONVENIENCE FUNCTION
# ============================================================

def generate_test_from_steps(
    test_name: str,
    steps: List[Dict[str, Any]],
    app_type: str = "auto"
) -> str:
    """
    Generate a test file from a list of step dictionaries.
    
    Args:
        test_name: Name for the test
        steps: List of step dicts with keys: action, description, target, value, selector
        app_type: Application type (salesforce, servicenow, etc.)
        
    Returns:
        Complete Python test file content
    """
    generator = FlowstralCodeGenerator(test_name, app_type)
    
    for step in steps:
        generator.add_step(
            action=step.get('action', 'click'),
            description=step.get('description', step.get('name', '')),
            target=step.get('target'),
            value=step.get('value'),
            selector=step.get('selector'),
            url=step.get('url'),
        )
    
    return generator.generate()

