/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "ok";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/generate-tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate structured test cases from requirements/context */
        post: operations["generateTests"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze failing test logs and artifacts for root cause & fixes */
        post: operations["triageFailure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a completed run with steps & artifacts */
        post: operations["ingestRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/integrations/jira/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive Jira issue updates (status, assignee, comments) */
        post: operations["jiraWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GenerateTestsRequest: {
            /** Format: uuid */
            org_id: string;
            /** Format: uuid */
            project_id: string;
            /** @description Free text or markdown spec */
            requirements: string;
            context?: {
                product_area?: string;
                acceptance_criteria?: string[];
                prior_flaky_cases?: string[];
                /** @enum {string} */
                style?: "gherkin" | "imperative";
                test_count_hint?: number;
            };
        };
        GenerateTestsResponse: {
            cases: components["schemas"]["TestCase"][];
            audit?: {
                model?: string;
                prompt_tokens?: number;
                completion_tokens?: number;
                cost_usd?: number;
                latency_ms?: number;
            };
        };
        TestCase: {
            /** Format: uuid */
            case_id?: string;
            title: string;
            description?: string;
            /** @enum {string} */
            priority: "P0" | "P1" | "P2" | "P3";
            tags?: string[];
            steps: components["schemas"]["TestStep"][];
        };
        TestStep: {
            action: string;
            data?: {
                [key: string]: unknown;
            };
            expected: string;
            locator_hints?: string[];
        };
        TriageRequest: {
            /** Format: uuid */
            org_id: string;
            /** Format: uuid */
            project_id: string;
            /** Format: uuid */
            run_id: string;
            /** @description Raw or structured logs */
            logs: string;
            artifacts?: components["schemas"]["Artifact"][];
        };
        TriageResponse: {
            summary: string;
            root_cause: string;
            /** @enum {string} */
            category?: "locator" | "timing" | "network" | "data" | "enviro";
            suggested_fixes?: string[];
            selector_suggestions?: string[];
            likelihood_flaky?: number;
            related_cases?: string[];
        };
        RunIngestRequest: {
            /** Format: uuid */
            org_id: string;
            /** Format: uuid */
            project_id: string;
            runner_version: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            completed_at: string;
            /** @enum {string} */
            status?: "passed" | "failed" | "partial" | "error";
            /** @enum {string} */
            environment?: "ci" | "local" | "staging" | "prod";
            branch?: string;
            commit?: string;
            steps?: {
                /** Format: uuid */
                case_id: string;
                title: string;
                /** @enum {string} */
                status: "passed" | "failed" | "skipped";
                duration_ms: number;
                error_message?: string;
                stdout?: string;
                stderr?: string;
                artifacts?: components["schemas"]["Artifact"][];
            }[];
        };
        Artifact: {
            /** @enum {string} */
            type: "screenshot" | "video" | "trace" | "har" | "log" | "other";
            /** Format: uri */
            url: string;
            size_bytes?: number;
            checksum?: string;
        };
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests */
        RateLimited: {
            headers: {
                /** @description seconds to wait */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generateTests: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateTestsRequest"];
            };
        };
        responses: {
            /** @description Structured test cases */
            200: {
                headers: {
                    "X-RateLimit-Limit"?: number;
                    "X-RateLimit-Remaining"?: number;
                    "X-RateLimit-Reset"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateTestsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["ServerError"];
        };
    };
    triageFailure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriageRequest"];
            };
        };
        responses: {
            /** @description Triage analysis */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["ServerError"];
        };
    };
    ingestRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIngestRequest"];
            };
        };
        responses: {
            /** @description Accepted for processing */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        run_id?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Payload too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ServerError"];
        };
    };
    jiraWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Acknowledge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
