import { useState } from "react";
import {
  GitBranch, GitPullRequest, Play, CheckCircle2, Settings,
  Copy, Download, ChevronRight, ChevronLeft, RefreshCw,
  Clock, Bell, Webhook, KeyRound, FileCode, Rocket
} from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { toast } from "sonner";

interface CICDConfig {
  provider: "github" | "gitlab" | "jenkins" | "azure" | "bitbucket";
  triggers: {
    onPush: boolean;
    onPullRequest: boolean;
    onSchedule: boolean;
    scheduleExpression?: string;
    branches: string[];
  };
  testSuites: string[];
  browsers: string[];
  parallel: number;
  notifications: {
    slack?: string;
    email?: string;
    teams?: string;
  };
  environment: {
    baseUrl?: string;
    headless: boolean;
    timeout: number;
  };
}

const PROVIDERS = [
  { id: "github", name: "GitHub Actions", icon: "🐙" },
  { id: "gitlab", name: "GitLab CI", icon: "🦊" },
  { id: "jenkins", name: "Jenkins", icon: "🔧" },
  { id: "azure", name: "Azure Pipelines", icon: "☁️" },
  { id: "bitbucket", name: "Bitbucket Pipelines", icon: "🪣" },
];

const TEST_SUITES = [
  { id: "smoke", name: "Smoke Tests", description: "Quick sanity checks" },
  { id: "regression", name: "Regression Suite", description: "Full regression tests" },
  { id: "api", name: "API Tests", description: "Backend API validation" },
  { id: "e2e", name: "E2E Tests", description: "End-to-end user flows" },
  { id: "accessibility", name: "Accessibility", description: "WCAG compliance checks" },
  { id: "performance", name: "Performance", description: "Load and performance tests" },
];

export default function CICDWizard() {
  const [step, setStep] = useState(1);
  const [config, setConfig] = useState<CICDConfig>({
    provider: "github",
    triggers: {
      onPush: true,
      onPullRequest: true,
      onSchedule: false,
      branches: ["main", "develop"],
    },
    testSuites: ["smoke", "regression"],
    browsers: ["chromium"],
    parallel: 2,
    notifications: {},
    environment: {
      headless: true,
      timeout: 30000,
    },
  });
  const [generatedConfig, setGeneratedConfig] = useState<string>("");

  const totalSteps = 5;

  const updateConfig = (path: string, value: any) => {
    setConfig(prev => {
      const newConfig = { ...prev };
      const keys = path.split(".");
      let current: any = newConfig;
      for (let i = 0; i < keys.length - 1; i++) {
        current = current[keys[i]];
      }
      current[keys[keys.length - 1]] = value;
      return newConfig;
    });
  };

  const generateConfig = () => {
    let configStr = "";
    
    switch (config.provider) {
      case "github":
        configStr = generateGitHubActions();
        break;
      case "gitlab":
        configStr = generateGitLabCI();
        break;
      case "jenkins":
        configStr = generateJenkinsfile();
        break;
      case "azure":
        configStr = generateAzurePipelines();
        break;
      case "bitbucket":
        configStr = generateBitbucketPipelines();
        break;
    }
    
    setGeneratedConfig(configStr);
    setStep(5);
  };

  const generateGitHubActions = () => {
    const triggers: string[] = [];
    if (config.triggers.onPush) {
      triggers.push(`  push:
    branches: [${config.triggers.branches.join(", ")}]`);
    }
    if (config.triggers.onPullRequest) {
      triggers.push(`  pull_request:
    branches: [${config.triggers.branches.join(", ")}]`);
    }
    if (config.triggers.onSchedule && config.triggers.scheduleExpression) {
      triggers.push(`  schedule:
    - cron: '${config.triggers.scheduleExpression}'`);
    }

    return `# ArisTrace - Automated Test Pipeline
# Generated by QA AI CI/CD Wizard

name: ArisTrace Automation

on:
${triggers.join("\n")}

env:
  QAAI_API_URL: \${{ secrets.QAAI_API_URL }}
  QAAI_API_KEY: \${{ secrets.QAAI_API_KEY }}
  BASE_URL: ${config.environment.baseUrl || "${{ vars.BASE_URL }}"}
  HEADLESS: ${config.environment.headless}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        browser: [${config.browsers.map(b => `"${b}"`).join(", ")}]
        shard: [${Array.from({ length: config.parallel }, (_, i) => i + 1).join(", ")}]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps \${{ matrix.browser }}
      
      - name: Run ${config.testSuites.join(", ")} tests
        run: |
          npx playwright test \\
            --project=\${{ matrix.browser }} \\
            --shard=\${{ matrix.shard }}/${config.parallel} \\
            --reporter=html,json
        env:
          TEST_SUITES: "${config.testSuites.join(",")}"
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-\${{ matrix.browser }}-\${{ matrix.shard }}
          path: |
            playwright-report/
            test-results/
          retention-days: 30
      
      - name: Report to ArisTrace
        if: always()
        run: |
          curl -X POST \${{ env.QAAI_API_URL }}/api/ci/report \\
            -H "Authorization: Bearer \${{ env.QAAI_API_KEY }}" \\
            -H "Content-Type: application/json" \\
            -d '{
              "run_id": "\${{ github.run_id }}",
              "status": "\${{ job.status }}",
              "browser": "\${{ matrix.browser }}",
              "shard": "\${{ matrix.shard }}",
              "commit": "\${{ github.sha }}",
              "branch": "\${{ github.ref_name }}"
            }'
${config.notifications.slack ? `
      - name: Notify Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: \${{ job.status }}
          webhook_url: \${{ secrets.SLACK_WEBHOOK }}
` : ""}
  
  merge-reports:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download all test results
        uses: actions/download-artifact@v4
        with:
          pattern: test-results-*
          merge-multiple: true
      
      - name: Merge reports
        run: npx playwright merge-reports ./all-results --reporter=html
      
      - name: Upload merged report
        uses: actions/upload-artifact@v4
        with:
          name: merged-playwright-report
          path: playwright-report/
          retention-days: 30`;
  };

  const generateGitLabCI = () => {
    return `# ArisTrace - GitLab CI Configuration
# Generated by QA AI CI/CD Wizard

stages:
  - test
  - report

variables:
  QAAI_API_URL: \${QAAI_API_URL}
  BASE_URL: ${config.environment.baseUrl || "$BASE_URL"}
  HEADLESS: "${config.environment.headless}"

.test_template: &test_template
  image: mcr.microsoft.com/playwright:v1.40.0-jammy
  stage: test
  timeout: 60 minutes
  script:
    - npm ci
    - npx playwright test --reporter=html,json
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
    expire_in: 30 days

${config.browsers.map(browser => `test:${browser}:
  <<: *test_template
  variables:
    BROWSER: "${browser}"
  parallel: ${config.parallel}
`).join("\n")}

report:
  stage: report
  image: curlimages/curl:latest
  needs: [${config.browsers.map(b => `"test:${b}"`).join(", ")}]
  script:
    - |
      curl -X POST \${QAAI_API_URL}/api/ci/report \\
        -H "Authorization: Bearer \${QAAI_API_KEY}" \\
        -H "Content-Type: application/json" \\
        -d '{
          "pipeline_id": "'\${CI_PIPELINE_ID}'",
          "status": "'\${CI_JOB_STATUS}'",
          "commit": "'\${CI_COMMIT_SHA}'",
          "branch": "'\${CI_COMMIT_REF_NAME}'"
        }'
  when: always`;
  };

  const generateJenkinsfile = () => {
    return `// ArisTrace - Jenkinsfile
// Generated by QA AI CI/CD Wizard

pipeline {
    agent any
    
    environment {
        QAAI_API_URL = credentials('qaai-api-url')
        QAAI_API_KEY = credentials('qaai-api-key')
        BASE_URL = '${config.environment.baseUrl || "${params.BASE_URL}"}'
        HEADLESS = '${config.environment.headless}'
    }
    
    options {
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    
    parameters {
        choice(name: 'BROWSER', choices: [${config.browsers.map(b => `'${b}'`).join(", ")}], description: 'Browser to run tests')
        string(name: 'BASE_URL', defaultValue: '${config.environment.baseUrl || ""}', description: 'Application URL')
    }
    
    stages {
        stage('Setup') {
            steps {
                sh 'npm ci'
                sh 'npx playwright install --with-deps \${BROWSER}'
            }
        }
        
        stage('Test') {
            steps {
                sh '''
                    npx playwright test \\
                        --project=\${BROWSER} \\
                        --reporter=html,json,junit
                '''
            }
            post {
                always {
                    publishHTML(target: [
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'playwright-report',
                        reportFiles: 'index.html',
                        reportName: 'Playwright Report'
                    ])
                    junit 'test-results/*.xml'
                }
            }
        }
        
        stage('Report') {
            steps {
                sh '''
                    curl -X POST \${QAAI_API_URL}/api/ci/report \\
                        -H "Authorization: Bearer \${QAAI_API_KEY}" \\
                        -H "Content-Type: application/json" \\
                        -d '{
                            "build_number": "'\${BUILD_NUMBER}'",
                            "status": "'\${currentBuild.result}'",
                            "commit": "'\${GIT_COMMIT}'",
                            "branch": "'\${GIT_BRANCH}'"
                        }'
                '''
            }
        }
    }
    
    post {
        failure {
            ${config.notifications.slack ? `slackSend(channel: '#qa-alerts', color: 'danger', message: "Test failed: \${env.JOB_NAME} #\${env.BUILD_NUMBER}")` : '// Add notification here'}
        }
    }
}`;
  };

  const generateAzurePipelines = () => {
    return `# ArisTrace - Azure Pipelines
# Generated by QA AI CI/CD Wizard

trigger:
${config.triggers.onPush ? `  branches:
    include:
${config.triggers.branches.map(b => `      - ${b}`).join("\n")}` : "  - none"}

${config.triggers.onPullRequest ? `pr:
  branches:
    include:
${config.triggers.branches.map(b => `      - ${b}`).join("\n")}` : ""}

${config.triggers.onSchedule ? `schedules:
  - cron: '${config.triggers.scheduleExpression || "0 2 * * *"}'
    displayName: 'Nightly run'
    branches:
      include:
        - main
    always: true` : ""}

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: qaai-secrets
  - name: BASE_URL
    value: '${config.environment.baseUrl || "$(BASE_URL)"}'
  - name: HEADLESS
    value: '${config.environment.headless}'

strategy:
  matrix:
${config.browsers.map(b => `    ${b}:
      BROWSER: '${b}'`).join("\n")}
  maxParallel: ${config.parallel}

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Setup Node.js'
  
  - script: npm ci
    displayName: 'Install dependencies'
  
  - script: npx playwright install --with-deps $(BROWSER)
    displayName: 'Install Playwright browsers'
  
  - script: |
      npx playwright test \\
        --project=$(BROWSER) \\
        --reporter=html,junit
    displayName: 'Run tests'
    env:
      TEST_SUITES: '${config.testSuites.join(",")}'
  
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results/*.xml'
      mergeTestResults: true
  
  - task: PublishPipelineArtifact@1
    condition: always()
    inputs:
      targetPath: 'playwright-report'
      artifact: 'playwright-report-$(BROWSER)'`;
  };

  const generateBitbucketPipelines = () => {
    return `# ArisTrace - Bitbucket Pipelines
# Generated by QA AI CI/CD Wizard

image: mcr.microsoft.com/playwright:v1.40.0-jammy

definitions:
  steps:
    - step: &test-step
        name: Run Tests
        caches:
          - node
        script:
          - npm ci
          - npx playwright test --reporter=html,json
        artifacts:
          - playwright-report/**
          - test-results/**

pipelines:
${config.triggers.onPush ? `  branches:
${config.triggers.branches.map(b => `    ${b}:
      - step: *test-step`).join("\n")}` : ""}

${config.triggers.onPullRequest ? `  pull-requests:
    '**':
      - step: *test-step` : ""}

${config.triggers.onSchedule ? `  custom:
    nightly-tests:
      - step: *test-step` : ""}`;
  };

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(generatedConfig);
      toast.success("Configuration copied to clipboard!");
    } catch (err) {
      toast.error("Failed to copy to clipboard");
    }
  };

  const downloadConfig = () => {
    const filename = config.provider === "github" ? ".github/workflows/qa-tests.yml" 
      : config.provider === "gitlab" ? ".gitlab-ci.yml"
      : config.provider === "jenkins" ? "Jenkinsfile"
      : config.provider === "azure" ? "azure-pipelines.yml"
      : "bitbucket-pipelines.yml";
    
    const blob = new Blob([generatedConfig], { type: "text/yaml" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename.split("/").pop() || "pipeline.yml";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success(`Downloaded ${filename}`);
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold gradient-text">CI/CD Wizard</h1>
          <p className="text-muted-foreground mt-1">
            Generate pipeline configurations for your QA tests
          </p>
        </div>
      </div>

      {/* Progress Steps */}
      <div className="flex items-center justify-between">
        {[
          { num: 1, label: "Provider" },
          { num: 2, label: "Triggers" },
          { num: 3, label: "Test Suites" },
          { num: 4, label: "Settings" },
          { num: 5, label: "Generate" },
        ].map((s, idx) => (
          <div key={s.num} className="flex items-center">
            <div 
              className={`flex items-center justify-center w-10 h-10 rounded-full font-medium transition-colors ${
                step >= s.num 
                  ? "bg-primary text-primary-foreground" 
                  : "bg-muted text-muted-foreground"
              }`}
            >
              {step > s.num ? <CheckCircle2 className="h-5 w-5" /> : s.num}
            </div>
            <span className={`ml-2 text-sm ${step >= s.num ? "font-medium" : "text-muted-foreground"}`}>
              {s.label}
            </span>
            {idx < 4 && <ChevronRight className="mx-4 h-5 w-5 text-muted-foreground" />}
          </div>
        ))}
      </div>

      {/* Step Content */}
      <Card className="min-h-[400px]">
        <CardContent className="pt-6">
          {/* Step 1: Provider Selection */}
          {step === 1 && (
            <div className="space-y-6">
              <div>
                <h3 className="text-lg font-semibold mb-4">Select CI/CD Provider</h3>
                <RadioGroup 
                  value={config.provider} 
                  onValueChange={(v) => updateConfig("provider", v)}
                  className="grid grid-cols-2 md:grid-cols-3 gap-4"
                >
                  {PROVIDERS.map(provider => (
                    <Label
                      key={provider.id}
                      htmlFor={provider.id}
                      className={`flex items-center gap-3 p-4 border rounded-lg cursor-pointer transition-colors ${
                        config.provider === provider.id 
                          ? "border-primary bg-primary/5" 
                          : "hover:bg-muted/50"
                      }`}
                    >
                      <RadioGroupItem value={provider.id} id={provider.id} />
                      <span className="text-2xl">{provider.icon}</span>
                      <span className="font-medium">{provider.name}</span>
                    </Label>
                  ))}
                </RadioGroup>
              </div>
            </div>
          )}

          {/* Step 2: Triggers */}
          {step === 2 && (
            <div className="space-y-6">
              <h3 className="text-lg font-semibold">Configure Triggers</h3>
              
              <div className="space-y-4">
                <div className="flex items-center justify-between p-4 border rounded-lg">
                  <div className="flex items-center gap-3">
                    <GitBranch className="h-5 w-5 text-primary" />
                    <div>
                      <p className="font-medium">On Push</p>
                      <p className="text-sm text-muted-foreground">Run tests when code is pushed</p>
                    </div>
                  </div>
                  <Checkbox 
                    checked={config.triggers.onPush}
                    onCheckedChange={(checked) => updateConfig("triggers.onPush", checked)}
                  />
                </div>

                <div className="flex items-center justify-between p-4 border rounded-lg">
                  <div className="flex items-center gap-3">
                    <GitPullRequest className="h-5 w-5 text-primary" />
                    <div>
                      <p className="font-medium">On Pull Request</p>
                      <p className="text-sm text-muted-foreground">Run tests on PR creation/update</p>
                    </div>
                  </div>
                  <Checkbox 
                    checked={config.triggers.onPullRequest}
                    onCheckedChange={(checked) => updateConfig("triggers.onPullRequest", checked)}
                  />
                </div>

                <div className="flex items-center justify-between p-4 border rounded-lg">
                  <div className="flex items-center gap-3">
                    <Clock className="h-5 w-5 text-primary" />
                    <div>
                      <p className="font-medium">Scheduled</p>
                      <p className="text-sm text-muted-foreground">Run tests on a schedule</p>
                    </div>
                  </div>
                  <Checkbox 
                    checked={config.triggers.onSchedule}
                    onCheckedChange={(checked) => updateConfig("triggers.onSchedule", checked)}
                  />
                </div>

                {config.triggers.onSchedule && (
                  <div className="ml-8 p-4 bg-muted/50 rounded-lg">
                    <Label>Cron Expression</Label>
                    <Input 
                      placeholder="0 2 * * *" 
                      className="mt-2"
                      value={config.triggers.scheduleExpression || ""}
                      onChange={(e) => updateConfig("triggers.scheduleExpression", e.target.value)}
                    />
                    <p className="text-xs text-muted-foreground mt-1">
                      Default: Daily at 2 AM UTC
                    </p>
                  </div>
                )}

                <div className="space-y-2">
                  <Label>Target Branches</Label>
                  <Input 
                    value={config.triggers.branches.join(", ")}
                    onChange={(e) => updateConfig("triggers.branches", e.target.value.split(",").map(b => b.trim()))}
                    placeholder="main, develop"
                  />
                </div>
              </div>
            </div>
          )}

          {/* Step 3: Test Suites */}
          {step === 3 && (
            <div className="space-y-6">
              <h3 className="text-lg font-semibold">Select Test Suites</h3>
              
              <div className="grid grid-cols-2 gap-4">
                {TEST_SUITES.map(suite => (
                  <div 
                    key={suite.id}
                    className={`p-4 border rounded-lg cursor-pointer transition-colors ${
                      config.testSuites.includes(suite.id) 
                        ? "border-primary bg-primary/5" 
                        : "hover:bg-muted/50"
                    }`}
                    onClick={() => {
                      const newSuites = config.testSuites.includes(suite.id)
                        ? config.testSuites.filter(s => s !== suite.id)
                        : [...config.testSuites, suite.id];
                      updateConfig("testSuites", newSuites);
                    }}
                  >
                    <div className="flex items-center justify-between">
                      <h4 className="font-medium">{suite.name}</h4>
                      <Checkbox checked={config.testSuites.includes(suite.id)} />
                    </div>
                    <p className="text-sm text-muted-foreground mt-1">{suite.description}</p>
                  </div>
                ))}
              </div>

              <div className="space-y-4 mt-6">
                <h4 className="font-medium">Browsers</h4>
                <div className="flex gap-4">
                  {["chromium", "firefox", "webkit"].map(browser => (
                    <Label
                      key={browser}
                      className={`flex items-center gap-2 p-3 border rounded-lg cursor-pointer ${
                        config.browsers.includes(browser) 
                          ? "border-primary bg-primary/5" 
                          : "hover:bg-muted/50"
                      }`}
                    >
                      <Checkbox 
                        checked={config.browsers.includes(browser)}
                        onCheckedChange={(checked) => {
                          const newBrowsers = checked
                            ? [...config.browsers, browser]
                            : config.browsers.filter(b => b !== browser);
                          updateConfig("browsers", newBrowsers);
                        }}
                      />
                      <span className="capitalize">{browser}</span>
                    </Label>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* Step 4: Settings */}
          {step === 4 && (
            <div className="space-y-6">
              <h3 className="text-lg font-semibold">Execution Settings</h3>
              
              <div className="grid md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <div>
                    <Label>Base URL</Label>
                    <Input 
                      placeholder="https://your-app.com"
                      value={config.environment.baseUrl || ""}
                      onChange={(e) => updateConfig("environment.baseUrl", e.target.value)}
                    />
                  </div>

                  <div>
                    <Label>Parallel Workers</Label>
                    <Select 
                      value={String(config.parallel)} 
                      onValueChange={(v) => updateConfig("parallel", parseInt(v))}
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        {[1, 2, 3, 4, 5, 6].map(n => (
                          <SelectItem key={n} value={String(n)}>{n} worker{n > 1 ? "s" : ""}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div>
                    <Label>Timeout (ms)</Label>
                    <Input 
                      type="number"
                      value={config.environment.timeout}
                      onChange={(e) => updateConfig("environment.timeout", parseInt(e.target.value))}
                    />
                  </div>

                  <div className="flex items-center gap-2">
                    <Checkbox 
                      id="headless"
                      checked={config.environment.headless}
                      onCheckedChange={(checked) => updateConfig("environment.headless", checked)}
                    />
                    <Label htmlFor="headless">Run in headless mode</Label>
                  </div>
                </div>

                <div className="space-y-4">
                  <h4 className="font-medium flex items-center gap-2">
                    <Bell className="h-4 w-4" />
                    Notifications
                  </h4>

                  <div>
                    <Label>Slack Webhook (optional)</Label>
                    <Input 
                      placeholder="https://hooks.slack.com/..."
                      value={config.notifications.slack || ""}
                      onChange={(e) => updateConfig("notifications.slack", e.target.value)}
                    />
                  </div>

                  <div>
                    <Label>Email (optional)</Label>
                    <Input 
                      placeholder="team@company.com"
                      value={config.notifications.email || ""}
                      onChange={(e) => updateConfig("notifications.email", e.target.value)}
                    />
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Step 5: Generated Config */}
          {step === 5 && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="text-lg font-semibold">Generated Configuration</h3>
                <div className="flex gap-2">
                  <Button variant="outline" size="sm" onClick={copyToClipboard}>
                    <Copy className="h-4 w-4 mr-2" />
                    Copy
                  </Button>
                  <Button variant="outline" size="sm" onClick={downloadConfig}>
                    <Download className="h-4 w-4 mr-2" />
                    Download
                  </Button>
                </div>
              </div>

              <div className="relative">
                <pre className="p-4 bg-zinc-950 text-zinc-100 rounded-lg overflow-auto max-h-[400px] text-sm font-mono">
                  {generatedConfig}
                </pre>
              </div>

              <Card className="bg-blue-50 dark:bg-blue-950 border-blue-200 dark:border-blue-800">
                <CardContent className="pt-4">
                  <h4 className="font-medium flex items-center gap-2 text-blue-700 dark:text-blue-300">
                    <KeyRound className="h-4 w-4" />
                    Required Secrets
                  </h4>
                  <ul className="mt-2 text-sm text-blue-600 dark:text-blue-400 space-y-1">
                    <li>• <code className="bg-blue-100 dark:bg-blue-900 px-1 rounded">QAAI_API_URL</code> - Your ArisTrace API URL</li>
                    <li>• <code className="bg-blue-100 dark:bg-blue-900 px-1 rounded">QAAI_API_KEY</code> - Your API key from Settings</li>
                    {config.notifications.slack && (
                      <li>• <code className="bg-blue-100 dark:bg-blue-900 px-1 rounded">SLACK_WEBHOOK</code> - Slack webhook URL</li>
                    )}
                  </ul>
                </CardContent>
              </Card>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Navigation Buttons */}
      <div className="flex justify-between">
        <Button 
          variant="outline" 
          onClick={() => setStep(Math.max(1, step - 1))}
          disabled={step === 1}
        >
          <ChevronLeft className="h-4 w-4 mr-2" />
          Back
        </Button>
        
        {step < 4 ? (
          <Button onClick={() => setStep(step + 1)}>
            Next
            <ChevronRight className="h-4 w-4 ml-2" />
          </Button>
        ) : step === 4 ? (
          <Button onClick={generateConfig}>
            <Rocket className="h-4 w-4 mr-2" />
            Generate Configuration
          </Button>
        ) : (
          <Button onClick={() => setStep(1)} variant="outline">
            <RefreshCw className="h-4 w-4 mr-2" />
            Start Over
          </Button>
        )}
      </div>
    </div>
  );
}

