apiVersion: v1
kind: Service
metadata:
  name: {{ include "qaai.fullname" . }}-frontend
  labels:
    {{- include "qaai.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "qaai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
