-- Migration: Test Data Management
-- Stores test data payloads generated alongside test cases

-- 1. Create test_data table
CREATE TABLE IF NOT EXISTS test_data (
    test_data_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    test_case_id UUID REFERENCES test_cases(test_case_id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    data_type VARCHAR(50) NOT NULL, -- 'json', 'csv', 'xml', 'form_data', 'query_params'
    payload JSONB NOT NULL, -- The actual test data
    is_synthetic BOOLEAN DEFAULT true, -- Generated by AI vs. manually created
    generated_by_llm BOOLEAN DEFAULT false, -- Generated during test case generation
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES users(user_id),
    org_id UUID REFERENCES organizations(org_id) ON DELETE CASCADE,
    project_id UUID REFERENCES projects(project_id) ON DELETE CASCADE,
    tenant_id UUID REFERENCES tenants(tenant_id) ON DELETE CASCADE
);

-- 2. Create test_data_templates table (reusable test data patterns)
CREATE TABLE IF NOT EXISTS test_data_templates (
    template_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(100), -- 'user', 'product', 'order', 'payment', 'api', etc.
    template_payload JSONB NOT NULL, -- Template with placeholders
    placeholders JSONB, -- List of placeholder variables
    org_id UUID REFERENCES organizations(org_id) ON DELETE CASCADE,
    project_id UUID REFERENCES projects(project_id) ON DELETE CASCADE,
    tenant_id UUID REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(org_id, project_id, name)
);

-- 3. Create indexes
CREATE INDEX IF NOT EXISTS idx_test_data_test_case ON test_data(test_case_id);
CREATE INDEX IF NOT EXISTS idx_test_data_tenant ON test_data(tenant_id);
CREATE INDEX IF NOT EXISTS idx_test_data_org_project ON test_data(org_id, project_id);
CREATE INDEX IF NOT EXISTS idx_test_data_templates_tenant ON test_data_templates(tenant_id);
CREATE INDEX IF NOT EXISTS idx_test_data_templates_category ON test_data_templates(category);

-- 4. Enable Row-Level Security
ALTER TABLE test_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE test_data_templates ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS policies
CREATE POLICY test_data_tenant_isolation ON test_data
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID OR tenant_id IS NULL);

CREATE POLICY test_data_templates_tenant_isolation ON test_data_templates
    FOR ALL
    USING (tenant_id = current_setting('app.current_tenant_id', true)::UUID OR tenant_id IS NULL);

-- 6. Create trigger to update updated_at
CREATE OR REPLACE FUNCTION update_test_data_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER test_data_updated_at
    BEFORE UPDATE ON test_data
    FOR EACH ROW
    EXECUTE FUNCTION update_test_data_updated_at();

-- 7. Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON test_data TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON test_data_templates TO authenticated;

COMMENT ON TABLE test_data IS 'Test data payloads generated alongside test cases';
COMMENT ON TABLE test_data_templates IS 'Reusable test data templates with placeholders';
COMMENT ON COLUMN test_data.generated_by_llm IS 'Indicates if test data was auto-generated during test case generation';

